FROM node:23

WORKDIR /app

## adding iproute2/iptables allow us to simulate network delay by running
## tc qdisc add dev eth0 root netem delay 100ms
RUN apt update && apt install -y iproute2 iptables tcpdump

COPY package.json package-lock.json ./
COPY src ./src
COPY dist ./dist
#COPY sysctl.conf /etc/sysctl.conf

## install deps so native binaries are in the correct format
RUN npm ci

ENTRYPOINT [ "node", "dist/gossip-peer.js" ]
